language: python
python:
- '2.7'
install:
- pip install "GitPython>=0.2.0-beta1" --use-mirrors
- mkdir -p vendors
- npm install git://github.com/jshint/jshint/
- npm install jscs
script:
- ./build.py dist -t -u -v
- jshint src/*.js
- jscs src/*.js
after_script:
- ./deploy.sh
env:
  global:
    secure: LdMLsA8jRSaDaRD9YNhre0fmDdlREPTjzluD/VhcW5OvKJAbAfQLi4hciueHe970TsunWMT4J7GV5VZ2uZbRrTpR+/svwmgF9AhszjIOjV75zCGA/3uNrETmzXZqwgtI5qZk+ucbLj9lPVWQiV7GutMdYxKDdn+Z1GkRWpJr5i8=
